### ISSUE TITLE
MAKEOPTS=-j. are ignored

### ISSUE THREAD

**Issue by apcel** [ASoft-se/Gentoo-HAI#10]
https://github.com/ASoft-se/Gentoo-HAI/blob/master/install.sh#L234
Here and at the next lines (#L244, #L252, ...) fresh-set  (#L157) MAKEOPTS  options are rewritten.

For example, if I have one core, portage will still be emerged using 8 threads

**Comment by NiKiZe** [comment]
-j. on emerge lines is not used for MAKEOPTS it is part of the emerge command to compile several packages in parallel.

from https://dev.gentoo.org/~zmedico/portage/doc/man/emerge.1.html:

> -j [JOBS], --jobs[=JOBS]
> Specifies the number of packages to build simultaneously. If this option is given without an argument, emerge will not limit the number of jobs that can run simultaneously. Also see the related --load-average option. Similarly to the --quiet-build option, the --jobs option causes all build output to be redirected to logs. Note that interactive packages currently force a setting of --jobs=1. This issue can be temporarily avoided by specifying --accept-properties=-interactive.

**Comment by apcel** [comment]
My fault. Sorry.

**Comment by NiKiZe** [comment]
No problem, thanks for your report.
Building multiple packages at once is mostly due to the high delay and idle CPU between packages when they are merged/installed to the running system. Some packages don't have any real compile stage at all and are just copying files.
