### ISSUE TITLE
Non-universal -j make flag

### ISSUE THREAD

**Issue by apcel** [ASoft-se/Gentoo-HAI#11]
https://github.com/ASoft-se/Gentoo-HAI/blob/dc888c3d0fb278cadc790631d7b9a7bd61b9dacb/install.sh#L348
Well, now I'm sure that -j option would be incorrect for many setups. The recommended value is $(($(nproc) + 1)), the real is always 16.

**Comment by NiKiZe** [comment]
Thanks
There is no "correct" or "incorrect" value of -j it is always a trade-of. How many processes can run in parallel and what does those processes do. There is also a spin up time and spin down between each and then there is use of other resources that is not CPU bound. I'd say that on modern hardware a good value is (virtual cores)*2

The goal here is to not have the CPU used as much as possible (no idle), you can test to have top open and run `make` on the kernel with different `-j` values ... there is also the `time make` which will tell you the real time it took to compile. even with 2, 4 or 8 cores I have found that -j16 is a good value when building the kernel as is done here.

When building system packages the number of cores is used, but the main reason for this is that the system is likely busy with different things, and might also be building multiple packages in parallel.

**Comment by apcel** [comment]
Well, okay. My measures showed me that "recommended" value used to work best, more threads leaded to less performance -- maybe I was missing something (but the more threads does gcc have, the more often cpu caches, disk sequential read, etc would be missed.. Am I wrong?)
Thanks.

**Comment by NiKiZe** [comment]
Again it depends on the type of load, are the tests you have run with the the Linux kernel? I can be wrong and maybe I should double test this, but if you can do the same I would appreciate it.

**Comment by apcel** [comment]
Unfortunately, I can re-test this only after Sunday morning
I'll try on different hardware (1-core and 4-core machines without ccache, ramdisk and other features; can't recall their specs now) then.

#And 16 threads consume more memory, of course! I bet that 384MB would not be enough for 16 threads :-)

**Comment by NiKiZe** [comment]
note that this is only used when setting up a new machine, and yes a minimum of 4GB of memory is assumed.

**Comment by NiKiZe** [comment]
(cat /proc/cpuinfo | grep -e name -e siblings | sort | uniq) ;\
echo -en nproc: ; nproc ;\
nj=$(($(nproc) * 3)); while [ $nj -gt 2 ]; do
   make clean > /dev/null; date && echo $nj && time (make -j$nj bzImage > /dev/null) && date
   : $((nj--))
done

VM: `Intel(R) Core(TM) i5 CPU         760  @ 2.80GHz`
siblings: 4, nproc:4

nproc:4 | -j3 | ***-j4*** | -j5 | -j6 | -j8 | -j12
---- | ---- | ---- | ---- | ---- | ---- | ----
real | 7m16.716s | ***5m32.805s*** | 5m34.497s | 5m35.354s | 5m38.011s  | 5m39.828s
user | 20m2.979s | 20m7.602s | 20m15.757s | 20m22.430s | 20m33.276s | 20m42.061s
sys  | 1m32.962s | 1m32.194s | 1m30.043s  | 1m28.236s  | 1m27.616s  | 1m25.937s 

bare with nvme: `Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz`
siblings: 8, nproc:8

nproc:8 | -j5        | -j6        | -j7        | -j8        | -j9        | -j10      | -j12    | ***-j16***       | -j21       | ***-j22***       | -j23       | -j24
----    | ----       | ----       | ----       | ----       | ----       | ----      | ----       | ----       | ---        | ----       | ----       | ----
real | 3m56.686s  | 3m5.133s   | 2m55.240s  | 2m46.326s  | 2m43.382s  | 2m38.997s | 2m38.354s  | ***2m37.891s***  | 2m38.572s  | ***2m37.562s***  | 2m37.998s  | 2m40.348s 
user | 13m49.036s | 16m21.392s | 17m12.424s | 17m36.084s | 17m48.556s | 18m5.952s | 18m12.748s | 18m23.492s | 18m29.060s | 18m30.480s | 18m30.688s | 18m27.868s
sys  | 0m29.504s  | 0m32.668s  | 0m34.228s  | 0m34.984s  | 0m34.008s  | 0m34.216s | 0m33.960s  | 0m33.824s  | 0m32.976s  | 0m33.216s  | 0m32.936s  | 0m45.876s 

From this I'd say that the best value usually is somewhere between `$(nproc)` and `$(nproc)*2`
But any degrade in range `$(nproc)` - `$(nproc)*3` is mostly neglectable
Let's go with `*$(nproc)*2`
