### ISSUE TITLE
Potentially removing a file from portage tree

### ISSUE THREAD

**Issue by apcel** [ASoft-se/Gentoo-HAI#12]
https://github.com/ASoft-se/Gentoo-HAI/blob/dc888c3d0fb278cadc790631d7b9a7bd61b9dacb/install.sh#L455
${PWD} at that line would be /usr/portage (#L435), and the chroot script is located at / (while in chroot), so removing /usr/portage/chrootstart.sh makes no sense.
Also, that script would be removed anyway at #L460

**Comment by NiKiZe** [comment]
Indeed, nice catch!
I would like to test if there is any side effects of removing it inside the chroot, but would you like to do a PR to fix this?
